# Application settings
check_interval: 2  # seconds

time_windows:
  - name: "Night Limit"
    start_time: "00:00"
    end_time: "06:00"
    mode: "blacklist" # 黑名单模式：列出的应用不允许运行
    app_list:
      - "chrome.exe"
      - "firefox.exe"
      - "steam.exe"
      - "epicgameslauncher.exe"
      - "valorant.exe"
      - "cs2.exe"
      - "discord.exe"
      - "telegram.exe"
      - "wechat.exe"
      - "qq.exe"
      # - "explorer.exe" # 限制文件管理器，防止通过它启动其他应用
      - "cmd.exe"
      - "powershell.exe"

# Hydra configuration (logging, output dirs, etc.)
hydra:
  run:
    # Create a run directory per execution; Hydra ensures it exists
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

  # output_subdir: null  # don't create an extra .hydra subdir under run dir

  # Ensure Hydra's own logs don't disable existing loggers
  hydra_logging:
    disable_existing_loggers: false

  # Configure application logging (root logger)
  job_logging:
    version: 1
    # formatters:
    #   simple:
    #     format: "%(asctime)s - %(levelname)s - %(name)s - %(message)s"
    #     datefmt: "%Y-%m-%d %H:%M:%S"
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra:run.dir}/sleeper_${now:%Y-%m-%d-%H}.log
        # Ensure Chinese characters are written correctly
        encoding: utf-8
    root:
      level: INFO
      handlers: [console, file]
    disable_existing_loggers: false