# Sleeper configuration
# Edit this file freely; changes are hot-reloaded automatically.

check_interval: 0.5 # seconds between active-window checks
log_dir: logs # relative to sleeper directory
override_max_minutes: 60 # maximum duration allowed for Emergency Override

time_windows:
  - name: "Night Limit"
    start_time: "00:00"
    end_time: "06:00"
    mode: "whitelist" # whitelist | blacklist
    force_kill: false # (blacklist only) kill the violating process
    app_list:
      - "explorer.exe"
      - "cmd.exe"
      - "powershell.exe"
      - "python.exe"
      - "pythonw.exe"
  - name: "DEBUG"
    start_time: "16:09"
    end_time: "16:11"
    mode: "blacklist"
    force_kill: false # (blacklist only) kill the violating process
    app_list:
      - "msedge.exe"
